### ISSUE TITLE
Remove hyprland and hyprland-git dependencies in the AUR please

### ISSUE THREAD

**Issue by Skerse** [kRHYME7/Hyprdots-ctl#1]
I can't install this package because right now i'm using the base Hyprland package from the main repos instead of the AUR. So when installing it says: 
> :: Conflicts found:
>     hyprland-git: hyprland 

Also, feels just unnecessary because the Hyprdots script will just install Hyprland anyway.

**Comment by kRHYME7** [comment]
Thanks! 
![image](https://github.com/kRHYME7/Hyprdots-ctl/assets/53417443/fe0b9336-1af2-476f-8a42-4d90c9b59fc4)

I will also try to add the PKGBUILD so that it will be easy to issue a PR.
