### ISSUE TITLE
[BUG]: Show binds not working

### ISSUE THREAD

**Issue by Oskar-Idland** [kRHYME7/Hyprdots-ctl#10]
Before pulling the recent update I was able to use `Hyprdots show binds` without any issues. Now I get the following:
![image](https://github.com/kRHYME7/Hyprdots-ctl/assets/69601310/93f0e1ed-4b0c-456f-a5c1-285bba985583)

My locale is set as you can see below:
![image](https://github.com/kRHYME7/Hyprdots-ctl/assets/69601310/b6a7348e-4306-41ab-b8f0-063b9c1d7a93)

And all other rofi related menus work like they should. I tried looking through the recent commits, but was not able to find what was wrong

**Comment by kRHYME7** [comment]
Thanks for the heads up!  Should be fixed on 08cb7365bc02a356ec1fa30d01c8bd817bdea15d
in AUR : ``` Hyprdots: v0.2.0.28.24012622 ```
