### ISSUE TITLE
Restoring the backup does not restore the theme and wallpaper

### ISSUE THREAD

**Issue by bluehysteric** [kRHYME7/Hyprdots-ctl#11]
I realized that after today's update, restoring the backup does not restore the theme and wallpaper, you need to change them manually.

**Comment by kRHYME7** [comment]
what do you mean by manually?

**Comment by bluehysteric** [comment]
> what do you mean by manually?
> 
> But the backup and restore functions are broken for now. I would suggest you don't use it right now.

I used Hyprdots backup revert to restore and the theme wallpaper did not come back after reboot. When will backup and restore fix it?

**Comment by kRHYME7** [comment]
Maybe this weekdays, 

By the way here is the corrected interpretation of the ./restore_cfg.sh( I just use this from the main repo hence that unexpected outcome). I will revise this so we can have the expected outputs. You'll see why Hyprdots backup and Hyprdots restore have unexpected outcomes. 


* YY: Both flags are set to 'Y'. 
In this case, the script will move the existing configuration to the backup directory (overwriting it) and then restore the new configuration from the clone directory.
* NN: Neither flag is set to 'Y'. 
The script will copy the existing configuration to the backup directory (preserving it) and then restore the new configuration from the clone directory.
* YN: The overwrite flag is set to 'Y' and the backup flag is not set to 'Y'.
 The script will move the existing configuration to the backup directory (overwriting it) and then restore the new configuration from the clone directory.
* NY: The overwrite flag is not set to 'Y' and the backup flag is set to 'Y'. 
The script will copy the existing configuration to the backup directory (preserving it) and then restore the new configuration from the clone directory.



I should be better off writing a slightly different approach as this is only designed to handle one way. It just overwrites and creates a backup for now. 

{Cloned-Hyprdots-repository-} >>>>{ git pull }>>>>>{ ``` ./install.sh r ``` } >>>>>>>>>>{ your configs }



**Posting this for the corrections**

**Comment by bluehysteric** [comment]
> Maybe this weekdays,
> 
> By the way here is the corrected interpretation of the ./restore_cfg.sh( I just use this from the main repo hence that unexpected outcome). I will revise this so we can have the expected outputs. You'll see why Hyprdots backup and Hyprdots restore have unexpected outcomes.
> 
> * YY: Both flags are set to 'Y'.
>   In this case, the script will move the existing configuration to the backup directory (overwriting it) and then restore the new configuration from the clone directory.
> * NN: Neither flag is set to 'Y'.
>   The script will copy the existing configuration to the backup directory (preserving it) and then restore the new configuration from the clone directory.
> * YN: The overwrite flag is set to 'Y' and the backup flag is not set to 'Y'.
>   The script will move the existing configuration to the backup directory (overwriting it) and then restore the new configuration from the clone directory.
> * NY: The overwrite flag is not set to 'Y' and the backup flag is set to 'Y'.
>   The script will copy the existing configuration to the backup directory (preserving it) and then restore the new configuration from the clone directory.
> 
> I should be better off writing a slightly different approach as this is only designed to handle one way. It just overwrites and creates a backup for now.
> 
> {Cloned-Hyprdots-repository-} >>>>{ git pull }>>>>>{ `./install.sh r` } >>>>>>>>>>{ your configs }
> 
> **Posting this for the corrections**

Understood. But I think that the backup: should backup the current configuration to the backup directory. Restore: restores from the backup directory to the current configuration directory.
That makes a bit more sense, don't you think?

**Comment by kRHYME7** [comment]
Hello @bluehysteric  I will close this as this seems a duplicate with #8  also here's how I perceive the overwrite and backup use cases 
https://github.com/kRHYME7/Hyprdots-ctl/discussions/12
