### ISSUE TITLE
/.cache/paru/clone/hyprdots-ctl/src/hyprdots-ctl

### ISSUE THREAD

**Issue by se7en-x230** [kRHYME7/Hyprdots-ctl#15]
Folder is spelled Hyprdots-cli with a capital H therefore paru breaks building

  cd "$srcdir/$pkgname" || return

takes the $pkgname which is spelled lower case

Bit confusing with the spellings

**Comment by kRHYME7** [comment]
@se7en-x230  thanks! Can you test it now?

**Comment by se7en-x230** [comment]
exellent
