### ISSUE TITLE
[Feature request]:- reduce height of pastebin 

### ISSUE THREAD

**Issue by Enigma1309** [kRHYME7/Hyprdots-ctl#16]
pastebin looks quite big, is there a way i can change it's height 
Original pastebin
![image](https://github.com/kRHYME7/Hyprdots-ctl/assets/94917588/6acb4e20-09bb-4565-bbf5-ea43fac2b0fe)

Hyprdots pastebin
![image](https://github.com/kRHYME7/Hyprdots-ctl/assets/94917588/02e995a8-3f9c-436c-9af5-edefbcfdf00c)

Height difference reveals a bit more could you decrease a little bit?

Thank you

**Comment by kRHYME7** [comment]
Hello, Reason for this is the original script uses 20%:55% w:h ratio and this will change through different sizes of monitors 


monitor 1 
![image](https://github.com/kRHYME7/Hyprdots-ctl/assets/53417443/899b6181-c044-4b53-a44e-b1837eb59255)
monitor 2  (wider monitor)
![image](https://github.com/kRHYME7/Hyprdots-ctl/assets/53417443/0d761dcd-840e-4118-bd46-bcdb9c66c436)


The  ``` Hyprdots show pastebin ``` uses a factor of width and use this as height, therefore using only the width size and having a good ratio across wider monitor. ( the height won't stretch depending on the height of the monitor )

monitor 1
![image](https://github.com/kRHYME7/Hyprdots-ctl/assets/53417443/632b1660-ddd1-4262-9c27-62ce96b4acd5)

monitor 2 (wider monitor)
![image](https://github.com/kRHYME7/Hyprdots-ctl/assets/53417443/1dba09cd-563f-4d8c-ba8a-6b74082cc679)
therefore achieving a consistent windows' height across all monitors. 

See the awkward difference for monitors that are wider. 


I recently pushed some changes in height, I agreed it's a bit longer.  I love to here some feedback. 🥂

**Comment by Enigma1309** [comment]
![image](https://github.com/kRHYME7/Hyprdots-ctl/assets/94917588/443c2ba7-62d5-4da0-bda9-30585ce9d892)
quite non related but
I've tried everything but this shows up, remove package and cache, clone and build locally but this seems to show no matter what i do

**Comment by kRHYME7** [comment]
What's the output for ``` Hyprdots version ```

**Comment by Enigma1309** [comment]
It's installed successfully but it kinda has this version duality
![image](https://github.com/kRHYME7/Hyprdots-ctl/assets/94917588/f19e0e74-635a-40eb-867f-fc91131061cb)
![image](https://github.com/kRHYME7/Hyprdots-ctl/assets/94917588/bfa594c6-0f77-4587-a925-0bcd685a24ae)

**Comment by kRHYME7** [comment]
It's natural, in AUR I use the the git version. Any changes from the repo will trigger a rebuild. Please ignore the Pkgbuild (3.5 ) as the aur helper will install the latest git version...

**Comment by kRHYME7** [comment]
Is the pastebin considerable Now? or should it be the same size as the original script.

**Comment by Enigma1309** [comment]
i haven't seen any changes yet, i've clean build it and i'm using aur

**Comment by Enigma1309** [comment]
Thanks it worked, now yay issues is also solved
