### ISSUE TITLE
[Discussion] Make disable-wallbash for spotify?

### ISSUE THREAD

**Issue by Radrahil** [kRHYME7/Hyprdots-ctl#17]
Should I work on this for the same thing as kitty?

**Comment by kRHYME7** [comment]
No, ``` ~/.config/hypr/scripts/wallbashspotify.sh ``` you can disable this script (chmod -x ). 
or yeah, just do it same as kitty but what ever the last set accent on your Spotify will persist therefore you need to configure it on your own. 

You can update, ``` hyprdots-ctl ``` I recently pushed a section for Spotify. 

![image](https://github.com/kRHYME7/Hyprdots-ctl/assets/53417443/871fe6c0-930d-4307-b8f0-afce355f024e)
