### ISSUE TITLE
Sync is not in the options anymore.

### ISSUE THREAD

**Issue by Xeo23** [kRHYME7/Hyprdots-ctl#18]
Sync is not in the options..

**Comment by kRHYME7** [comment]
Hello, Sorry for removing without a warning. It'll be back as soon As I can port it to the new ./hyprdots/ directory.  Thanks for informing this.

**Comment by kRHYME7** [comment]
Added https://github.com/kRHYME7/Hyprdots-ctl/commit/5484b52871649a65d0e81d1e4b49564386d6a5de back
