### ISSUE TITLE
Changing Shell

### ISSUE THREAD

**Issue by dieBakterie** [kRHYME7/Hyprdots-ctl#20]
An option to change the shell and theme from fish to zsh and from zsh to fish

**Comment by kRHYME7** [comment]
@dieBakterie  ``` Hyprdots shell select ```  

fcdd058bf745cb4722d92d7e297dc44f70e0d898

**Comment by dieBakterie** [comment]
Ok i'll try it later and should i select `lib32-nvdia-utils` as lib32-vulkan-driver i'm on Nvidia
