### ISSUE TITLE
Always get "You are using an older version of Hyprdots!..."

### ISSUE THREAD

**Issue by Oskar-Idland** [kRHYME7/Hyprdots-ctl#23]
I have read the README multiple times and tried to reinstall and everything. Whatever command i try to use i get the same message:
```
❯ Hyprdots --version
You are using an older version of Hyprdots! Please see upstream to adjust your configuration.
```
```
❯ Hyprdots man
You are using an older version of Hyprdots! Please see upstream to adjust your configuration.
```
What am I doing wrong?

**Comment by kRHYME7** [comment]
Are you using the older Directory?

the ``` ~/.config/hypr/scripts ``` is moved to ``` ~/.config/hypr/scripts ``` .

Lemme add this to read me for now.

**Comment by Oskar-Idland** [comment]
Yes, it seems I have the old directory! I read the issue you sent, and had some issues, but most were solvable. To anyone reading this later, remember to:
1. Rename the folder from `~/.config/hypr` to `~/.config/hyprdots`
2. Go into `` and rename the variabel `$srcPath` to `$scrPath = ~/.config/hyprdots/scripts`
3. Go into `keybinds_hints.sh` and rename `keyConfDir` to `keyConfDir="$ConfDir/hyprdots"
`

Some paths to be edited I could not find. When running `Hyprdots reload` I get:
```sh
cat: /home/oskar/.config/hypr/theme.ctl: No such file or directory
cat: /home/oskar/.config/hypr/theme.ctl: No such file or directory
Unknown theme selected: 
Available themes are:
cat: /home/oskar/.config/hypr/theme.ctl: No such file or directory
```
which tells me there are more paths to be edited. I could not find the script being ran by the reload command. Do you know where to find it, or what specific paths to edit?

**Comment by Oskar-Idland** [comment]
Whoops broke the entire config on reboot. Do not just rename the hypr folder (obviously), just follow the guide on issue above

**Comment by kRHYME7** [comment]
Sorry did not Read this earlier, So I could stop you HAHa. 

BTWE we are having a discord channel, this is not complete but would be open for some suggestions.

**Comment by Oskar-Idland** [comment]
@kRHYME7 What do you mean "open to some suggestions"? Would love to join anyways. Where can I find it?

**Comment by Oskar-Idland** [comment]
Solved by updating using [this issue](https://github.com/prasanthrangan/hyprdots/issues/1053). There were other problems post-update, but the `Hyprdots` command works as it should.

**Comment by kRHYME7** [comment]
> Hyprdots show binds does not work still, but that might be a separate issue

I now use the key binds hint from the Hyprdots repo, so Hyprdots show binds and ./keybindhints.sh will be the same.

**Comment by Oskar-Idland** [comment]
The invite became invalid. Would you please add "xz82_" when you have the time?
