### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Skerse** [kRHYME7/Hyprdots-ctl#6]
I'm sure you're fine with full copying, modifying, and distribution of this software, but i still think it'd be great to have a license. Maybe GPL v3 would be fine, since Hyprdots is licensed with that.

**Comment by kRHYME7** [comment]
Yup Planning to have that too, But I wanted to dig deeper on that Licensing thingy as some of my script might be from others. Might do this this week.

**Comment by kRHYME7** [comment]
@Skerse  Ill be closing this now. Thanks!
