### ISSUE TITLE
Keybinds issue?

### ISSUE THREAD

**Issue by Enigma1309** [kRHYME7/Hyprdots-ctl#7]
![image](https://github.com/kRHYME7/Hyprdots-ctl/assets/94917588/21626d51-7df9-4f32-9914-d4a47cdfccf8)

I'm getting this issue running the script and also i'm getting no output

![image](https://github.com/kRHYME7/Hyprdots-ctl/assets/94917588/b4dd874a-d201-4682-b56f-a07e3a187177)

**Comment by kRHYME7** [comment]
Thanks for reporting this, unfortunately having a json and parsing  a doubleqoute  " will surely give this error.  I'll try to fix this but for now try this solutions...


+ Changing double-qoute into single-qoute
example: 
```bind = $mainMod, grave, exec, $HOME/Scripts/Special  'Console - Alacritty' 'console' '~/Scripts/Launcher/Console-Alacritty'  ``` for now comment wont become a description.  

+  adding that array of command into a script

**Comment by Enigma1309** [comment]
Okay this was such a silliy issue now it's fixed btw what nerd font i've to download??
Font seems broken
![image](https://github.com/kRHYME7/Hyprdots-ctl/assets/94917588/41660b76-821c-4cc2-afc1-affcbb0adac9)

**Comment by kRHYME7** [comment]
I'll be honest I do not really know how I managed to view this penguin without installing new font so maybe I should experiment on a new arch install. 
the icon  I use is ' nf-linux-locos '
Got this all from here https://www.nerdfonts.com/cheat-sheet



󰌽
󰻀
 

I'll try to use a more generic icon or an icon that is installed together with Hyprdots. 

Thanks!

**Comment by Enigma1309** [comment]
I installed JetBrains Nerd font and my icons are working 😀

**Comment by Enigma1309** [comment]
![image](https://github.com/kRHYME7/Hyprdots-ctl/assets/94917588/184ff8f3-722e-4233-89da-98aedfe275ae)

Hard coded somewhere

**Comment by kRHYME7** [comment]
> I installed JetBrains Nerd font and my icons are working 😀

It works now? 


> Hard coded somewhere
Oh I see I forgot to revert this! Thanks ! it works on my test machine as it has the same file tree.

**Comment by Enigma1309** [comment]
> Keybinding works now?

Yeah it works, after replacing "" to ''

**Comment by kRHYME7** [comment]
Issues should be fixed at version  ```║Hyprdots: v0.2.0.18.24010902 ║```  , you can update in the AUR

Won't get an error if the user uses d-qoutes "" but it cannot parse comments.

**Comment by kRHYME7** [comment]
@Enigma1309  Hi! Issue should all be settled on commit ``` cbbbe5afae43ca807f39548beacfb89bbb6e7d6f ``` version ``` v0.2.0.19.24011109 ``` . I will close this for now
