### ISSUE TITLE
Simple Script to record screen

### ISSUE THREAD

**Issue by se7en-x230** [kRHYME7/Hyprdots-ctl#9]
Having a simple screen recorder available would be appreciated.

**Comment by kRHYME7** [comment]
Hello! For the meantime, I will implement the screencorder using wf-recorder as it just works for the majority.  
As wl-screenrec needs some setting-up of vaapi for some devices. This might cause a bunch of issues.

**Comment by kRHYME7** [comment]
Hello dunno if this is simple but here you go. 

```
❯ Hyprdots run screencap
Screenrecord: 'wl-screenrec'
Screenshot: 'grimblast'

[Usage] Hyprdots run screencap [option]

-pa|--print-all                 󰄀 Print all outputs
-ra|--record-all                󰃽 Record all outputs if supported by the screenrecorder, default to focused monitor
-ps|--print-snip                󰄀 Drag to manually snip an area
-rs|--record-snip               󰃽 Drag to manually snip an area to screen record it
-f|--freeze                     󰄀 Frozen screen, drag to manually snip an area
-pm|--print-monitor             󰄀 Print focused monitor
--stop                           Stop every instance of Screencap

For Screen Recording you can pass an argument (--help for for options for 'wl-screenrec' )
Example you can append [--audio] to capture audio.

```

For now we have two options for screen recording 
```
-rs|--record-snip               󰃽 Drag to manually snip an area to screen record it
-ra|--record-all                󰃽 Record all outputs if supported by the screenrecorder, default to focused monitor
```
I did not add focused monitor yet as I don't have an extra monitor yet

**Comment by se7en-x230** [comment]
Amazing work. Thanks works fine

**Comment by se7en-x230** [comment]
https://github.com/kRHYME7/Hyprdots-ctl/assets/69777713/01f19670-d189-41d4-89ba-2ff8f172f314

**Comment by se7en-x230** [comment]
The video format does not play on android.
At least not on Telegram.

**Comment by se7en-x230** [comment]
#! Oh no! wl-screenrec is not working for you. Do not worry we will use wf-recorder instead. Try to run 'wl-screenrec' in termianl.
screen_recorder="wf-recorder"

**Comment by kRHYME7** [comment]
Have you tried using wl-screenrec on terminal?

**Comment by se7en-x230** [comment]
Yes I guess it's a codec problem with android
I have to look into what exact codec works

**Comment by se7en-x230** [comment]
Nope.canr ger wl-screenrec work at all

**Comment by kRHYME7** [comment]
@se7en-x230  Hello, May I ask do you have intel or amd GPU ?

**Comment by se7en-x230** [comment]
I am a Intel user as they usually just work under linux

**Comment by kRHYME7** [comment]
I think wl-screenrec might work for you.  For intel users 
```
libva-intel-driver 
intel-media-driver 
```

If it does I will add checks to install this packages for screen recording.

**Comment by se7en-x230** [comment]
I will test and report tomorrow

**Comment by se7en-x230** [comment]
I had to change -ra into -rf (focused) and now it works including sound. That is with wf-recorder

bind = $mainMod, o, exec,  Hyprdots run screencap -rf -a 
bind = $mainMod Shift, o, exec, Hyprdots run screencap --stop

**Comment by se7en-x230** [comment]
https://github.com/kRHYME7/Hyprdots-ctl/assets/69777713/66b7cfff-e97b-4768-957e-ea972fe68982
